BBPATH:prepend := "${LAYERDIR}:"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "wendyos-tegra"
BBFILE_PATTERN_wendyos-tegra := "^${LAYERDIR}/"
BBFILE_PRIORITY_wendyos-tegra = "51"

LAYERSERIES_COMPAT_wendyos-tegra = "scarthgap whinlatter"
LAYERVERSION_wendyos-tegra = "1"
LAYERDEPENDS_wendyos-tegra = "core wendyos"
