require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/bblayers/core.inc
require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/bblayers/oe-common.inc
require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/bblayers/rpi-wendy.inc
require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/bblayers/wendyos.inc

