SUMMARY = "Crypt stack and TPM PCR policy for the /data partition"
DESCRIPTION = "Puts the LUKS2 + TPM userspace on the image and generates \
/etc/data-crypt.conf, the TPM PCR policy the /data resolver reads when it seals \
a keyslot. The resolver (wendyos-data.service, from the data-device recipe) \
owns the conversion and the boot-time unlock. This recipe exists so the tools \
that work needs are present, and so the PCR list is a build-time setting \
rather than something baked into the script. It also ships \
/usr/sbin/data-recovery-key, which mints a LUKS recovery key on demand after \
the conversion, because the conversion itself enrols none. Board-agnostic; \
pulled into an image by the per-board image include when \
WENDYOS_DATA_ENCRYPTED=1."
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

PR = "r0"

SRC_URI = " \
    file://data-recovery-key \
    "

# /etc/data-crypt.conf is not here: it is generated in do_install below.
S = "${UNPACKDIR}"

# Board-agnostic: parsed on every machine but only pulled into an image when
# WENDYOS_DATA_ENCRYPTED=1 (see the per-board image includes), so no
# COMPATIBLE_MACHINE restriction. The kernel TPM driver and the meta-tpm layer
# are wired per board.

# PCR policy for the TPM keyslot, consumed by the resolver
# (/usr/sbin/wendyos-data.sh) via /etc/data-crypt.conf. Default "7" (x86 legacy:
# Secure Boot state). Empty = SRK-only (no PCR binding) -- a board sets
# WENDYOS_TPM_PCRS = "" to opt into that (Jetson does, until secure boot lands).
WENDYOS_TPM_PCRS ?= "7"

do_install() {
    install -d ${D}${sysconfdir}
    cat > ${D}${sysconfdir}/data-crypt.conf <<EOF
# Generated by the data-crypt recipe. Sourced by /usr/sbin/wendyos-data.sh.
# TPM_PCRS: PCR list for systemd-cryptenroll --tpm2-pcrs; empty = SRK-only.
TPM_PCRS="${WENDYOS_TPM_PCRS}"
EOF

    # No .sh suffix: this is a command an operator and the wendy CLI invoke by
    # name, not an implementation detail of a unit.
    install -d ${D}${sbindir}
    install -m 0755 ${UNPACKDIR}/data-recovery-key ${D}${sbindir}/data-recovery-key
}

CONFFILES:${PN} = "${sysconfdir}/data-crypt.conf"

FILES:${PN} = " \
    ${sysconfdir}/data-crypt.conf \
    ${sbindir}/data-recovery-key \
    "

# The crypt stack the resolver looks up at runtime. Without one of these it
# reports no_support and leaves /data plain, so each entry is named by the call
# site it feeds in wendyos-data.sh:
#   cryptsetup            luksFormat, open, close, luksUUID
#   systemd-crypt         systemd-cryptenroll (TPM + recovery key) and
#                         systemd-cryptsetup attach (the boot-time unlock)
#   gptfdisk              sgdisk -e, to move the GPT backup header to the disk end
#   parted                parted resizepart and partprobe
#   e2fsprogs-mke2fs      mkfs.ext4, inside the new container
#   coreutils             basename, readlink, cat, head, date, tr, sync
#   udev                  udevadm settle
#   util-linux-wipefs     wipefs, for a stale or unfinished LUKS header
#   util-linux-blkdiscard blkdiscard, which the mandatory zero-fill before
#                         luksFormat needs; without it the resolver refuses the
#                         conversion with no_support. Cited by name, not by
#                         line: that check sits in the tool sweep just
#                         above the conversion in wendyos-data.sh, and a
#                         line number here goes stale every time that
#                         file is edited -- as this one already had
# util-linux-lsblk is gone: its only user was the migration guard, which the
# resolver replaced.
RDEPENDS:${PN} = " \
    cryptsetup \
    systemd-crypt \
    gptfdisk \
    parted \
    e2fsprogs-mke2fs \
    coreutils \
    udev \
    util-linux-wipefs \
    util-linux-blkdiscard \
    "
