# jetson-agx-thor: NVIDIA Jetson AGX Thor Developer Kit (NVMe).
# split-poky composition on whinlatter, no Mender / no OTA.

require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/local/common.inc
require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/local/usb-gadget.inc
require ${TOPDIR}/../${WENDYOS_META_REPO}/conf/template/include/local/tegra-t264.inc

DEVICE  = "jetson-agx-thor"
STORAGE = "nvme"
MACHINE = "jetson-agx-thor-devkit-nvme-wendyos"
