BBPATH:prepend := "${LAYERDIR}:"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "wendyos-tegra-jp6"
BBFILE_PATTERN_wendyos-tegra-jp6 := "^${LAYERDIR}/"
BBFILE_PRIORITY_wendyos-tegra-jp6 = "52"

LAYERSERIES_COMPAT_wendyos-tegra-jp6 = "scarthgap"
LAYERVERSION_wendyos-tegra-jp6 = "1"
LAYERDEPENDS_wendyos-tegra-jp6 = "core wendyos wendyos-tegra"

BBFILE_PATTERN_IGNORE_EMPTY_wendyos-tegra-jp6 = "1"
