BBPATH:prepend := "${LAYERDIR}:"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "wendyos-rpi"
BBFILE_PATTERN_wendyos-rpi := "^${LAYERDIR}/"
BBFILE_PRIORITY_wendyos-rpi = "51"

LAYERSERIES_COMPAT_wendyos-rpi = "scarthgap"
LAYERVERSION_wendyos-rpi = "1"
LAYERDEPENDS_wendyos-rpi = "core wendyos"
