BBPATH:prepend := "${LAYERDIR}:"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "wendyos-qemu"
BBFILE_PATTERN_wendyos-qemu := "^${LAYERDIR}/"
BBFILE_PRIORITY_wendyos-qemu = "51"

LAYERSERIES_COMPAT_wendyos-qemu = "scarthgap"
LAYERVERSION_wendyos-qemu = "1"
LAYERDEPENDS_wendyos-qemu = "core wendyos"
