#!/bin/sh
# Make this devkit usable on the machine it was unpacked on, then verify it runs.
#
# uninative bakes absolute paths into every native binary: an ELF interpreter pointing at
# one bundled glibc, and a library search path inside that loader. Until both are rewritten
# nothing under toolchain/ or kernel-build/scripts/ can start outside its build tree.
set -eu

D=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
RUNTIME="$D/runtime"

# Assigned then eval'd rather than eval'd inline: `eval "$(cmd)"` reports eval's status, so
# a failed read would look like success and leave every field empty.
read_json() {
    python3 - "$@" <<'PY'
import json, shlex, sys
doc = json.load(open(sys.argv[1]))
for spec in sys.argv[2:]:
    var, _, path = spec.partition("=")
    node = doc
    for key in path.split("."):
        node = (node or {}).get(key)
    print("%s=%s" % (var, shlex.quote(node or "")))
PY
}

devkit_vars=$(read_json "$D/devkit.json" CROSS=cross_compile TC_BINDIR=toolchain_bindir \
    ORIG_LOADER=original_loader KVER=kernel_version) \
    || { echo "devkit setup: cannot read $D/devkit.json" >&2; exit 1; }
eval "$devkit_vars"
BINDIR="$D/$TC_BINDIR"

# Taken from the loader uninative recorded, so the build host's architecture is not assumed.
LOADER="$RUNTIME/lib/$(basename "$ORIG_LOADER")"
[ -x "$LOADER" ] || { echo "devkit setup: no loader at $LOADER" >&2; exit 1; }

# oe-core ships relocate_sdk.py with a literal ##DEFAULT_INSTALL_DIR## that the SDK
# installer replaces with the path baked into the binaries. These were built against the
# uninative sysroot, so substitute that instead.
OLD_PREFIX=$(dirname "$(dirname "$ORIG_LOADER")")
sed "s|##DEFAULT_INSTALL_DIR##|$OLD_PREFIX|g" "$D/relocate_sdk.py" > "$D/.relocate.py"

# Rewrites both each binary's PT_INTERP and the loader's own library search path; with only
# the former the binaries start and then fail to find libc. PT_INTERP is patched in place,
# so the new path must be no longer than the original — unpack the devkit somewhere short.
find "$D/toolchain" "$D/kernel-build/scripts" "$D/hosttools" "$RUNTIME" \
        -type f -perm -u+x -print0 2>/dev/null \
    | xargs -0 -r python3 "$D/.relocate.py" "$RUNTIME" "$LOADER"
rm -f "$D/.relocate.py"

# PATH only. LD_LIBRARY_PATH would apply to every process, so host tools such as python3
# and make would load this devkit's glibc and fail on GLIBC_PRIVATE mismatches; the search
# path rewritten above already scopes it to the devkit's own binaries.
cat > "$D/env.sh" <<EOSH
# Generated by setup.sh. Source this before using the devkit's toolchain.
export PATH="$BINDIR\${PATH:+:\$PATH}"
EOSH
chmod 0644 "$D/env.sh"

# A devkit that unpacks cleanly but cannot run its own tools fails silently until the first
# driver build, so check each one here.
"$BINDIR/${CROSS}gcc" --version >/dev/null 2>&1 \
    || { echo "devkit setup: ${CROSS}gcc still will not run" >&2; exit 1; }
# modpost exits non-zero on --help by design, so match the loader error instead of a status.
if "$D/kernel-build/scripts/mod/modpost" --help 2>&1 | grep -q 'loading shared libraries'; then
    echo "devkit setup: modpost cannot resolve its libraries" >&2; exit 1
fi
"$D/hosttools/mksquashfs" -version >/dev/null 2>&1 \
    || { echo "devkit setup: mksquashfs will not run" >&2; exit 1; }

echo "devkit ready: $D"
echo "  kernel: $KVER"
